### ISSUE TITLE
More example notebooks

### ISSUE THREAD

**Issue by SamDuffield** [CQCL/qujax#84]
Naturally would be good to expand the suite of notebooks to demonstrate more use cases.

One option be might to investigate barren plateaus under various circuits/observables/initialisations.

Of course, ideas welcomed!

**Comment by gamatos** [comment]
I'm putting together a barren plateaus notebook, will open a PR with that soon 🙂

**Comment by gamatos** [comment]
Barren plateaus notebook will be getting added in #99. Closing this issue for now, we can open another issue if we think of any other notebooks that should be implemented.
